parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  node: true
extends:
  - airbnb-base
  - prettier
rules:
  no-unused-vars: off
  no-param-reassign: off
  no-unused-expressions: off
  no-await-in-loop: off
  no-constant-condition: off
